### ISSUE TITLE
support for phalcon 2.x

### ISSUE THREAD

**Issue by krzysztof-kabala** [vegas-cmf/core#52]
hi guys, Would be grat to move vegas to XXI century :)

I found some issues which not allow to run vegas (core) on phalcon 2.x env. After simple code refactor I got working vegas on newest phalcon without any errors.
## 1
- ErrorException: Argument 1 passed to Phalcon\Config::merge() must be an instance of Phalcon\Config, array given, called in /vendor/vegas-cmf/core/src/Mvc/Bootstrap.php on line 142 and defined
  /vendor/vegas-cmf/core/src/Bootstrap/ModulesInitializerTrait.php (57)

solution:

> /vendor/vegas-cmf/core/src/Bootstrap/ModulesInitializerTrait.php:57

`$config->merge(new Config($moduleConfig));`
## 2
- [:error] [pid 28696] [client 127.0.0.1:54134] PHP Strict Standards:  Declaration of Vegas\Mvc\Application::registerModules() should be compatible with Phalcon\Mvc\Application::registerModules(array $modules, $merge = NULL) in /vendor/vegas-cmf/core/src/Mvc/Application.php on line 0

solution:

> /vendor/vegas-cmf/core/src/Mvc/Application.php:41

`public function registerModules(array $modules, $merge = null)`
## 3
- [:error] [pid 28696] [client 127.0.0.1:54134] PHP Fatal error:  Declaration of Vegas\DI\InjectionAwareTrait::setDI($dependencyInjector) must be compatible with Phalcon\Di\InjectionAwareInterface::setDI(Phalcon\DiInterface $dependencyInjector) in /vendor/vegas-cmf/core/src/Mvc/Router.php on line 265

solution:

> /vendor/vegas-cmf/core/src/DI/InjectionAwareTrait.php:38

`public function setDI(DiInterface $dependencyInjector)`
## 4
- [:error] [pid 28690] [client 127.0.0.1:54150] PHP Fatal error:  Declaration of Vegas\Mvc\ModuleAbstract::registerAutoloaders() must be compatible with Phalcon\Mvc\ModuleDefinitionInterface::registerAutoloaders(Phalcon\DiInterface $dependencyInjector = NULL) in /vendor/vegas-cmf/core/src/Mvc/ModuleAbstract.php on line 23

solution:

> /vendor/vegas-cmf/core/src/Mvc/ModuleAbstract.php:42

`public function registerAutoloaders(DiInterface $dependencyInjector = null)`
## 5
- [:error] [pid 28688] [client 127.0.0.1:54154] PHP Fatal error:  Declaration of Vegas\Mvc\ModuleAbstract::registerServices() must be compatible with Phalcon\Mvc\ModuleDefinitionInterface::registerServices(Phalcon\DiInterface $dependencyInjector) in /vendor/vegas-cmf/core/src/Mvc/ModuleAbstract.php on line 24

solution:

> /vendor/vegas-cmf/core/src/Mvc/ModuleAbstract.php:78

`public function registerServices(DiInterface $di)`
## 6
- ErrorException: Declaration of Vegas\Mvc\View::_engineRender() should be compatible with Phalcon\Mvc\View::_engineRender($engines, $viewPath, $silence, $mustClean, Phalcon\Cache\BackendInterface $cache = NULL)
  /vendor/vegas-cmf/core/src/Mvc/View.php (0)

solution:

> /vendor/vegas-cmf/core/src/Mvc/View.php:99

`protected function _engineRender($engines, $viewPath, $silence, $mustClean, BackendInterface $cache = null)`

Its core issues only, but rest of modules is going over the hill.
Bon Appetit! :)

**Comment by arius86** [comment]
We are working currently on 2.x branch (you can see that it is here in repository). Thanks for your effort, sadly all those fixes are already known by us and fixed in 2.x branch.
