### ISSUE TITLE
Undefined variable: record

### ISSUE THREAD

**Issue by krzysztof-kabala** [vegas-cmf/core#64]
Whoops\Exception\ErrorException: Undefined variable: record in file /opt/cache/_opt_vendor_vegas-cmf_core_src_mvc_controller_crud_views_edit.volt.php on line 17
Stack trace:
  1. Whoops\Exception\ErrorException->() /opt/cache/_opt_vendor_vegas-cmf_core_src_mvc_controller_crud_views_edit.volt.php:17
  2. Whoops\Run->handleError() /opt/cache/_opt_vendor_vegas-cmf_core_src_mvc_controller_crud_views_edit.volt.php:17
  3. Phalcon\Mvc\View\Engine\Volt->render() /opt/vendor/vegas-cmf/core/src/Mvc/View.php:188
  4. Vegas\Mvc\View->_engineRender() [internal]:0
  5. Phalcon\Mvc\View->render() /opt/vendor/vegas-cmf/core/src/Mvc/View.php:394
  6. Vegas\Mvc\View->render() /opt/vendor/vegas-cmf/core/src/Mvc/Controller/CrudAbstract.php:52
  7. Vegas\Mvc\Controller\CrudAbstract->Vegas\Mvc\Controller\{closure}() [internal]:0
  8. Phalcon\Events\Manager->fireQueue() [internal]:0
  9. Phalcon\Events\Manager->fire() /opt/vendor/vegas-cmf/core/src/Mvc/View.php:210
 10. Vegas\Mvc\View->_engineRender() [internal]:0
 11. Phalcon\Mvc\View->render() /opt/vendor/vegas-cmf/core/src/Mvc/View.php:394
 12. Vegas\Mvc\View->render() [internal]:0
 13. Phalcon\Mvc\View->getRender() /opt/vendor/vegas-cmf/forms/src/Decorator.php:115
 14. Vegas\Forms\Decorator->generatePartial() /opt/vendor/vegas-cmf/forms/src/Decorator.php:70
 15. Vegas\Forms\Decorator->render() /opt/vendor/vegas-cmf/forms/src/Decorator/DecoratedTrait.php:58
 16. Vegas\Forms\Element\Cloneable->baseRenderDecorated() /opt/vendor/vegas-cmf/forms/src/Element/Cloneable.php:146
 17. Vegas\Forms\Element\Cloneable->renderDecorated() /opt/cache/_opt_app_modules_product_views_admin_product_partial__render_elements.volt.php:93
 18. Phalcon\Mvc\View\Engine\Volt->render() /opt/vendor/vegas-cmf/core/src/Mvc/View.php:188
 19. Vegas\Mvc\View->_engineRender() [internal]:0
 20. Phalcon\Mvc\View->partial() /opt/vendor/vegas-cmf/core/src/Mvc/View.php:412
 21. Vegas\Mvc\View->partial() [internal]:0
 22. Phalcon\Mvc\View\Engine->partial() /opt/cache/_opt_app_modules_product_views_admin_product__form.volt.php:27
 23. Phalcon\Mvc\View\Engine\Volt->render() /opt/vendor/vegas-cmf/core/src/Mvc/View.php:188
 24. Vegas\Mvc\View->_engineRender() [internal]:0
 25. Phalcon\Mvc\View->partial() /opt/vendor/vegas-cmf/core/src/Mvc/View.php:412
 26. Vegas\Mvc\View->partial() [internal]:0
 27. Phalcon\Mvc\View\Engine->partial() /opt/cache/_opt_app_modules_product_views_admin_product_edit.volt.php:5
 28. Phalcon\Mvc\View\Engine\Volt->render() /opt/vendor/vegas-cmf/core/src/Mvc/View.php:188
 29. Vegas\Mvc\View->_engineRender() [internal]:0
 30. Phalcon\Mvc\View->render() /opt/vendor/vegas-cmf/core/src/Mvc/View.php:394
 31. Vegas\Mvc\View->render() [internal]:0
 32. Phalcon\Mvc\Application->handle() /opt/vendor/vegas-cmf/core/src/Mvc/Bootstrap.php:162
 33. Vegas\Mvc\Bootstrap->run() /opt/public/index.php:26

+

Whoops\Exception\ErrorException: Undefined variable: form in file /opt/cache/_opt_vendor_vegas-cmf_core_src_mvc_controller_crud_views_new.volt.php on line 18
Stack trace:
  1. Whoops\Exception\ErrorException->() /opt/cache/_opt_vendor_vegas-cmf_core_src_mvc_controller_crud_views_new.volt.php:18
  2. Whoops\Run->handleError() /opt/cache/_opt_vendor_vegas-cmf_core_src_mvc_controller_crud_views_new.volt.php:18
  3. Phalcon\Mvc\View\Engine\Volt->render() /opt/vendor/vegas-cmf/core/src/Mvc/View.php:188
  4. Vegas\Mvc\View->_engineRender() [internal]:0
  5. Phalcon\Mvc\View->render() /opt/vendor/vegas-cmf/core/src/Mvc/View.php:394
  6. Vegas\Mvc\View->render() /opt/vendor/vegas-cmf/core/src/Mvc/Controller/CrudAbstract.php:52
  7. Vegas\Mvc\Controller\CrudAbstract->Vegas\Mvc\Controller\{closure}() [internal]:0
  8. Phalcon\Events\Manager->fireQueue() [internal]:0
  9. Phalcon\Events\Manager->fire() /opt/vendor/vegas-cmf/core/src/Mvc/View.php:210
 10. Vegas\Mvc\View->_engineRender() [internal]:0
 11. Phalcon\Mvc\View->render() /opt/vendor/vegas-cmf/core/src/Mvc/View.php:394
 12. Vegas\Mvc\View->render() [internal]:0
 13. Phalcon\Mvc\View->getRender() /opt/vendor/vegas-cmf/forms/src/Decorator.php:115
 14. Vegas\Forms\Decorator->generatePartial() /opt/vendor/vegas-cmf/forms/src/Decorator.php:70
 15. Vegas\Forms\Decorator->render() /opt/vendor/vegas-cmf/forms/src/Decorator/DecoratedTrait.php:58
 16. Vegas\Forms\Element\Cloneable->baseRenderDecorated() /opt/vendor/vegas-cmf/forms/src/Element/Cloneable.php:146
 17. Vegas\Forms\Element\Cloneable->renderDecorated() /opt/cache/_opt_vendor_vegas-cmf_core_src_mvc_controller_crud_views_new.volt.php:33
 18. Phalcon\Mvc\View\Engine\Volt->render() /opt/vendor/vegas-cmf/core/src/Mvc/View.php:188
 19. Vegas\Mvc\View->_engineRender() [internal]:0
 20. Phalcon\Mvc\View->render() /opt/vendor/vegas-cmf/core/src/Mvc/View.php:394
 21. Vegas\Mvc\View->render() /opt/vendor/vegas-cmf/core/src/Mvc/Controller/CrudAbstract.php:52
 22. Vegas\Mvc\Controller\CrudAbstract->Vegas\Mvc\Controller\{closure}() [internal]:0
 23. Phalcon\Events\Manager->fireQueue() [internal]:0
 24. Phalcon\Events\Manager->fire() /opt/vendor/vegas-cmf/core/src/Mvc/View.php:210
 25. Vegas\Mvc\View->_engineRender() [internal]:0
 26. Phalcon\Mvc\View->render() /opt/vendor/vegas-cmf/core/src/Mvc/View.php:394
 27. Vegas\Mvc\View->render() [internal]:0
 28. Phalcon\Mvc\Application->handle() /opt/vendor/vegas-cmf/core/src/Mvc/Bootstrap.php:162
 29. Vegas\Mvc\Bootstrap->run() /opt/public/index.php:26

**Comment by archdevil666pl** [comment]
This is an issue in vegas-cmf/forms. Fixed in [#bed7a13](https://github.com/vegas-cmf/forms/commit/bed7a131f0117e2ae24b4c5cde25e6b9f1e3e2bc#diff-9dcb7ae94ee44ca5ec0d89b23d39decdL103).
